[package]
name = "spreadsheet"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.10.2"  
libc = "0.2"
clap = "4.4.11"
once_cell = "1.18"

lazy_static = "1.4.0"
ratatui = "0.23.0"
crossterm = "0.27.0"
egui = "0.24"
eframe = "0.24"
